package com.elara.script.parser;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, COLON, DOT, SEMICOLON,
    PLUS, MINUS, STAR, DOUBLE_STAR, SLASH, PERCENT,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    AND_AND, OR_OR,

    IDENTIFIER, STRING, NUMBER,

    LET, IF, ELSE, WHILE, FOR, TRUE, FALSE, NULL,
    FUNCTION, RETURN, BREAK,
    CLASS, DEF, NEW, FREE,

    EOF
}